stages:
  - build
  - package
  - release

build:darwin:amd64:
  stage: build
  image: golang:1.21-alpine
  script:
    - GOOS=darwin GOARCH=amd64 go build -o ./bin/darwin/amd64/git-lfs-s3-caching-adapter
  artifacts:
    paths:
      - bin/darwin/amd64/git-lfs-s3-caching-adapter
    expire_in: 2 hours
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  tags:
    - cri

build:darwin:arm64:
  stage: build
  image: golang:1.21-alpine
  script:
    - GOOS=darwin GOARCH=arm64 go build -o ./bin/darwin/arm64/git-lfs-s3-caching-adapter
  artifacts:
    paths:
      - bin/darwin/arm64/git-lfs-s3-caching-adapter
    expire_in: 2 hours
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  tags:
    - cri

build:linux:amd64:
  stage: build
  image: golang:1.21-alpine
  script:
    - GOOS=linux GOARCH=amd64 go build -o ./bin/linux/amd64/git-lfs-s3-caching-adapter
  artifacts:
    paths:
      - bin/linux/amd64/git-lfs-s3-caching-adapter
    expire_in: 2 hours
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  tags:
    - cri

build:linux:arm64:
  stage: build
  image: golang:1.21-alpine
  script:
    - GOOS=linux GOARCH=arm64 go build -o ./bin/linux/arm64/git-lfs-s3-caching-adapter
  artifacts:
    paths:
      - bin/linux/arm64/git-lfs-s3-caching-adapter
    expire_in: 2 hours
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  tags:
    - cri

package:
  stage: package
  image:
    name: helium.cr/toolbox/multitool:latest
    entrypoint: [""]
  script:
    - cd bin
    - if [ "$(uname -m)" == "x86_64" ]; then export ARCH='amd64'; elif [ "$(uname -m)" == "aarch64" ]; then export ARCH='arm64'; else exit 1; fi
    - export RELEASE_VERSION=$(linux/${ARCH}/git-lfs-s3-caching-adapter version --short)
    - sha256sum darwin/amd64/git-lfs-s3-caching-adapter > darwin/amd64/git-lfs-s3-caching-adapter.sha256
    - sha256sum darwin/arm64/git-lfs-s3-caching-adapter > darwin/arm64/git-lfs-s3-caching-adapter.sha256
    - sha256sum linux/amd64/git-lfs-s3-caching-adapter > linux/amd64/git-lfs-s3-caching-adapter.sha256
    - sha256sum linux/arm64/git-lfs-s3-caching-adapter > linux/arm64/git-lfs-s3-caching-adapter.sha256
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "darwin/amd64/git-lfs-s3-caching-adapter.sha256" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-amd64.sha256"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "darwin/amd64/git-lfs-s3-caching-adapter" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-amd64"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "darwin/arm64/git-lfs-s3-caching-adapter.sha256" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-arm64.sha256"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "darwin/arm64/git-lfs-s3-caching-adapter" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-arm64"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "linux/amd64/git-lfs-s3-caching-adapter.sha256" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-amd64.sha256"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "linux/amd64/git-lfs-s3-caching-adapter" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-amd64"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "linux/arm64/git-lfs-s3-caching-adapter.sha256" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-arm64.sha256"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "linux/arm64/git-lfs-s3-caching-adapter" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-arm64"'
    - cd ..
    - printenv | grep RELEASE_ > release.env
  artifacts:
    expire_in: 2 hours
    paths:
      - bin/**/*.sha256
    reports:
      dotenv: release.env
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: manual
  tags:
    - cri

release:gitlab:
  stage: release
  image:
    name: helium.cr/toolbox/multitool:latest
    entrypoint: [""]
  script: "echo Performing release of Git LFS S3 caching adapter ${RELEASE_VERSION} to HeliumNet GitLab..."
  release:
    tag_name: ${RELEASE_VERSION}
    tag_message: Git LFS S3 caching adapter ${RELEASE_VERSION}
    name: Git LFS S3 caching adapter v${RELEASE_VERSION}
    ref: $CI_COMMIT_SHA
    description: 'Release version ${RELEASE_VERSION} of the Git LFS S3 caching adapter.'
    assets:
      links:
        - name: macOS amd64
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-amd64"
          filepath: /darwin/amd64/git-lfs-s3-caching-adapter
          link_type: other
        - name: macOS amd64 sha256sum
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-amd64.sha256"
          filepath: /darwin/amd64/git-lfs-s3-caching-adapter.sha256
          link_type: other
        - name: macOS arm64
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-arm64"
          filepath: /darwin/arm64/git-lfs-s3-caching-adapter
          link_type: other
        - name: macOS arm64 sha256sum
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-darwin-arm64.sha256"
          filepath: /darwin/arm64/git-lfs-s3-caching-adapter.sha256
          link_type: other
        - name: linux amd64
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-amd64"
          filepath: /linux/amd64/git-lfs-s3-caching-adapter
          link_type: other
        - name: linux amd64 sha256sum
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-amd64.sha256"
          filepath: /linux/amd64/git-lfs-s3-caching-adapter.sha256
          link_type: other
        - name: linux arm64
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-arm64"
          filepath: /linux/arm64/git-lfs-s3-caching-adapter
          link_type: other
        - name: linux arm64 sha256sum
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/git-lfs-s3-caching-adapter/${RELEASE_VERSION}/git-lfs-s3-caching-adapter-linux-arm64.sha256"
          filepath: /linux/arm64/git-lfs-s3-caching-adapter.sha256
          link_type: other
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  tags:
    - cri

release:github:
  stage: release
  image:
    name: helium.cr/toolbox/multitool:latest
    entrypoint: [""]
  script:
    - "echo Performing release of Git LFS S3 caching adapter ${RELEASE_VERSION} to GitHub..."
    - git remote add github git@github.com:RemcodM/git-lfs-s3-caching-adapter.git
    - >
        gh release create "${RELEASE_VERSION}"
          --notes "Release version ${RELEASE_VERSION} of the Git LFS S3 caching adapter."
          --title "Git LFS S3 caching adapter v${RELEASE_VERSION}"
          --repo "RemcodM/git-lfs-s3-caching-adapter"
          --verify-tag
          "bin/darwin/amd64/git-lfs-s3-caching-adapter#git-lfs-s3-caching-adapter-darwin-amd64"
          "bin/darwin/amd64/git-lfs-s3-caching-adapter.sha256#git-lfs-s3-caching-adapter-darwin-amd64.sha256"
          "bin/darwin/arm64/git-lfs-s3-caching-adapter#git-lfs-s3-caching-adapter-darwin-arm64"
          "bin/darwin/arm64/git-lfs-s3-caching-adapter.sha256#git-lfs-s3-caching-adapter-darwin-arm64.sha256"
          "bin/linux/amd64/git-lfs-s3-caching-adapter#git-lfs-s3-caching-adapter-linux-amd64"
          "bin/linux/amd64/git-lfs-s3-caching-adapter.sha256#git-lfs-s3-caching-adapter-linux-amd64.sha256"
          "bin/linux/arm64/git-lfs-s3-caching-adapter#git-lfs-s3-caching-adapter-linux-arm64"
          "bin/linux/arm64/git-lfs-s3-caching-adapter.sha256#git-lfs-s3-caching-adapter-linux-arm64.sha256"
  needs:
    - package
    - release:gitlab
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  tags:
    - cri
